name: CD Deploy
on:
  push:
    branches:
      - 'develop'
      - 'main'
    paths:
      - 'infrastructure/mlflow/**'

env:
  AWS_DEFAULT_REGION: "eu-north-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # Plan infrastructure for MLFlow server
      - name: TF Plan MLFlow
        id: tf-plan
        working-directory: "infrastructure/mlflow"
        run: |
          terraform init -backend-config="key=flight-price-prediction-mlflow-prod.tfstate" --reconfigure && terraform plan --var-file vars/prod.tfvars

      # Apply infrastructure for MLFlow server
      - name: TF Apply MLFlow
        id: tf-apply
        working-directory: "infrastructure/mlflow"
        if: ${{ steps.tf-plan.outcome }} == 'success'
        run: |
          terraform apply -auto-approve --var-file vars/prod.tfvars
