name: CI Tests
on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'app/**'
      - 'tests/'
      - 'integration-tests/'

env:
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
            python-version: 3.11.9

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: false

      - name: Install dependencies
        run: poetry lock --no-update && poetry install

      - name: Run Unit tests
        run: poetry run pytest tests/

      - name: Linting
        run: poetry run pylint --recursive=y .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Integration Tests
        working-directory: "./integration-test"
        run: |
          . run.sh
